### ISSUE TITLE
Implement Protobuff

### ISSUE THREAD

**Issue by jordan-bentley** [jordan-bentley/encrypted_mail_server#1]
Create a method in both classes for serializing and de-serializing data prior to encryption.

**Comment by RobertHosking** [comment]
Also, we'll need to form our message into an object:

Not quite sure what the object should look like. Discuss below:
```
message {
action: ???,
??

}
```

**Comment by RobertHosking** [comment]
## Steps:

- [x] create a `.proto` file with our object declarations (see above comment for structure)
- [x] compile that file `protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/addressbook.proto` [Docs](https://developers.google.com/protocol-buffers/docs/pythontutorial)
- [x] import the generated python file in our class code
- [x] create a message
- [x] serialize and send
- [ ] read message
